---
- name: install homebrew cask
  homebrew:
    name: caskroom/cask/brew-cask
    state: present

- name: Install some casks
  homebrew_cask:
    name: "{{ item }}"
    state: present
  environment:
      HOMEBREW_CASK_OPTS: --appdir=/Applications
  with_items:
    - dropbox
    - flux
    - google-chrome
    - iterm2
    - spectacle
    - spotify
    - 1password
